app:
  id: spring-cloud-gateway
apollo:
  meta: ${apollo_meta:http://apolloconfig.dev.wyyt:8640/}
  bootstrap:
    enabled: true
    namespaces: Architecture.spring-cloud-common,Architecture.gateway,Architecture.gateway,application
    eagerLoad:
      enabled: true

server:
  port: ${gateway_server_port:80}
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: ${gateway_consul_name}
    group: ${gateway_consul_group}
    version: 1.0
  redis:
    host: ${redis_host}
    port: ${redis_port}
    password: ${redis_password}
    timeout: ${redis_timeout}
    database: ${redis_database}
    jedis:
      pool:
        max-active: ${redis-max-active}
        max-idle: ${redis-max-idle}
        min-idle: ${redis-min-idle}
  zipkin:
    sender:
      type: kafka
  kafka:
    bootstrap-servers: ${zipkin_kafka_servers}