# Apollo Config
app:
  # Apollo的AppId(类似ACM中的DataId)
  id: sms
apollo:
  # apollo_meta需配置在环境变量中
  meta: ${apollo_meta:http://apolloconfig.dev.wyyt:8640/}
  bootstrap:
    enabled: true
    namespaces: Architecture.spring-cloud-common,application
    eagerLoad:
      enabled: true

server:
  port: 1001

spring:
  servlet:
    multipart:
      # 文件上传大小配置
      max-request-size: 100MB
      max-file-size: 10MB
  application:
    name: sms
    group: sms
    # 版本号, 每次发布必须填写不同的版本号, 且建议版本号是递增
    version: 1.0
    strategy:
      scan:
        # 指定对业务RestController类的扫描路径。此项配置作用于RPC方式的调用拦截、消费端的服务隔离和调用链三项功能
        packages: org.springcloud.sms.controller
  cloud:
    consul:
      host: ${consul_host}
      port: ${consul_port}
  zipkin:
    sender:
      type: kafka
  kafka:
    bootstrap-servers: ${zipkin_kafka_servers}

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl