apollo:
  app-id: bams-db2es

sharding:
  enabled: false
  work-id: 100
  show-sql: false
  apollo:
    app-id: ${apollo.app-id}
    data-source-key: datasource
    dimension-key: dimension
    table-key: table

admin:
  ui:
    title: DB2ES管理综合平台
    full-name: DB2ES管理综合平台
    short-name: DB2ES管理综合平台
    login-mode: ldap

server:
  port: ${db2es.admin.port:10088}
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
  servlet:
    session:
      timeout: 180m
      tracking-modes: cookie
      cookie:
        http-only: true
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: db2es-admin
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  aop:
    proxy-target-class: true
  jmx:
    default-domain: ${spring.application.name}
  freemarker:
    allow-session-override: true
    check-template-location: true
    suffix: .ftl
    content-type: text/html
    enabled: true
    cache: false
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    charset: UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: request
    settings:
      auto_import: common/spring.ftl as spring
      number_format: '0.##'
  ldap:
    base: "DC=sijibao,DC=com"
    username: "ldap"                                           # 配置管理员账号，用于搜索、匹配用户
    password: "ijiP9rJ7Oe40AiXq[{ks28Xgeltsc00p"               # 配置管理员密码，用于搜索、匹配用户
    urls:
      - "ldap://ldap.sijibao.com:38900"
    mapping:
      object-class-attr-name: "user"                           # ldap 用户 objectClass 配置
      login-id-attr-name: "sAMAccountName"                     # ldap 用户唯一id，用来作为登录的 id
      name-attr-name: "description"                            # ldap 用户名，用来作为显示名
      mail-attr-name: "mail"                                   # ldap 邮箱属性
      phone-number-attr-name: "mobile"                         # ldap 手机属性
      title-attr-name: "title"                                 # ldap 职位属性

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true