app:
  id: spring-cloud-gateway
apollo:
  meta: ${apollo_meta:http://apolloconfig.dev.wyyt:8640/}
  bootstrap:
    enabled: true
    namespaces: Architecture.spring-cloud-common,Architecture.gateway,Architecture.gateway,application
    eagerLoad:
      enabled: true

admin:
  ui:
    title: Spring Cloud 智能网关管理平台
    full-name: Spring Cloud 智能网关
    short-name: Spring Cloud 智能网关
    login-mode: ldap

server:
  port: ${gateway_admin_server_port:81}
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
  servlet:
    session:
      timeout: 180m
      tracking-modes: cookie
      cookie:
        http-only: true
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: ${gateway_admin_consul_name}
  cloud:
    consul:
      host: ${consul_host}
      port: ${consul_port}
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
    loadbalancer:
      ribbon:
        enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  aop:
    proxy-target-class: true
  jmx:
    default-domain: ${spring.application.name}
  freemarker:
    allow-session-override: true
    check-template-location: false
    suffix: .ftl
    content-type: text/html;charset=utf-8
    enabled: true
    cache: false
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    charset: UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: request
    settings:
      auto_import: common/spring.ftl as spring
      number_format: '0.##'
  redis:
    host: ${redis_host}
    port: ${redis_port}
    password: ${redis_password}
    timeout: ${redis_timeout}
    database: ${redis_database}
    jedis:
      pool:
        max-active: ${redis-max-active}
        max-idle: ${redis-max-idle}
        min-idle: ${redis-min-idle}
  ldap:
    base: "DC=sijibao,DC=com"
    username: "ldap"                                           # 配置管理员账号，用于搜索、匹配用户
    password: "ijiP9rJ7Oe40AiXq[{ks28Xgeltsc00p"               # 配置管理员密码，用于搜索、匹配用户
    urls:
      - "ldap://ldap.sijibao.com:38900"
    mapping:
      object-class-attr-name: "user"                           # ldap 用户 objectClass 配置
      login-id-attr-name: "sAMAccountName"                     # ldap 用户唯一id，用来作为登录的 id
      name-attr-name: "description"                            # ldap 用户名，用来作为显示名
      mail-attr-name: "mail"                                   # ldap 邮箱属性
      phone-number-attr-name: "mobile"                         # ldap 手机属性
      title-attr-name: "title"                                 # ldap 职位属性

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"